### ISSUE TITLE
Adding new SEO to an Entry

### ISSUE THREAD

**Issue by cmh208** [brodjustice/semi_static#1]
Hi, 
I have encountered a possible bug when attempting to add a new SEO to an Entry.

Normally, from the Entries list, I used to be able to click the green "+" button and a Form to create a new SEO would pop-up.

Right now, the Form for a new SEO is not presented. Would appreciate any help/pointers.

Thanks,

c.

**Comment by brodjustice** [comment]
Ok, thanks have issued a bug fix
