### ISSUE TITLE
SEO Dialog panel, missing field labels

### ISSUE THREAD

**Issue by cmh208** [brodjustice/semi_static#10]
Not sure if this is a general "bug".

The dialog panel for setting SEO appears to missing labels for fields, attached - a screenshot:

![admin dashboard for armin l rau](https://cloud.githubusercontent.com/assets/16307935/23366124/e1899596-fd05-11e6-852d-b58dd6682882.png)

**Comment by brodjustice** [comment]
This is not a SemiStatic bug as such, rather an error in the custom CSS for arminlrau.com. Still, keep it here as it does need to be fixed.

**Comment by brodjustice** [comment]
FIxed in new SemiStatic dashboard layout
