### ISSUE TITLE
"Events", price: cents not displayed

### ISSUE THREAD

**Issue by cmh208** [brodjustice/semi_static#11]
![warum bin ich so wie ich bin](https://cloud.githubusercontent.com/assets/16307935/23908080/45ad31da-08d3-11e7-8c67-bfc70267bce5.png)

A small problem:

The actual cost of an Event is € 99,90 - however the "cents" part is displayed as "00"

**Comment by brodjustice** [comment]
I can't recreate this on the latest version of SemiStatic. Maybe try it on justice-communications.com.

**Comment by cmh208** [comment]
Seems to be fixed:
![Home](https://user-images.githubusercontent.com/16307935/54199782-0e915980-44ca-11e9-90e5-4c42bb0b097b.png)

The "button" to register looks like a normal linked text but this is probably because the css is not the same as Anke's.
