### ISSUE TITLE
Galleries that are not public cannot be used as Entry Gallery slideshow

### ISSUE THREAD

**Issue by brodjustice** [brodjustice/semi_static#17]
This was probably don't on purpose to stop accidental sharing of non-public galleries, but it seems this is just restrictive, we should let the user do what they want.

**Comment by cmh208** [comment]
hmmm, i'm probably getting confused here, but in eco marketing all the galleries are set to public:

![capture](https://user-images.githubusercontent.com/16307935/38774645-3a2694ae-406e-11e8-9568-ccf238846b8c.JPG)

In the older entry for example, can view the slideshow:[http://economic-marketing.com/entries/66-anniversary-party-munich]( http://economic-marketing.com/entries/66-anniversary-party-munich) 

![capture](https://user-images.githubusercontent.com/16307935/38774683-0201900a-406f-11e8-94fc-dcea3f61af45.JPG)

But with the new "News" entries, looks like this: [http://economic-marketing.com/entries/93-summer-event-in-strassburg](http://economic-marketing.com/entries/93-summer-event-in-strassburg) 

![capture](https://user-images.githubusercontent.com/16307935/38774725-b6e715d0-406f-11e8-90fb-5c949cc6e92d.JPG)

Not sure if this is going to be hard to resolve. If it is, will need to set expectations etc.

**Comment by brodjustice** [comment]
I think you are mixing a lot of different things up there. Try this:
1) Add a merged Entry to that "Summer Event In Strassburg"
2) In the merged Entry now set the "Gallery" (in the sidebar in the admin for the Entry) to "Strassburg Sommer" (I think that is what it is called) and you should now get a proper slideshow with buttons and everything.

**Comment by cmh208** [comment]
yes, this is fixed
