### ISSUE TITLE
Thomas's website: Logo masking the menu labels, effects tablets

### ISSUE THREAD

**Issue by cmh208** [brodjustice/semi_static#25]
Probably not a big issue right now as it's too early - but needs to be noted.

If you look at the LP using a tablet in landscape, the menu labels "Blog" and "Bewegung" cannot be clicked because the wide logo such as we have is masking them… if you know what i mean.

**Comment by brodjustice** [comment]
Can we close this now as it's not directly related to the Gem and is stale anyway?

**Comment by cmh208** [comment]
Yes, will close
