### ISSUE TITLE
Cannot update admin password

### ISSUE THREAD

**Issue by brodjustice** [brodjustice/semi_static#36]
System reports that password is updated, but it is actually not changed.

**Comment by cmh208** [comment]
Probably related - but cannot create new Admin accounts either.

**Comment by cmh208** [comment]
Well. actually a new account can be created - but cannot login using the defined credentials.

**Comment by brodjustice** [comment]
Yes. It's related. The problem is that Rails 5 is very strict with it's parameters and rejects the new password unless it is specifically allowed. So in the SemiStatic generator we need to looks at:
`        generate(:scaffold, @admin_model_name + " name:string surname:string")`
Will test this out shortly

**Comment by brodjustice** [comment]
Closed by https://github.com/brodjustice/semi_static/commit/70c61cd500bad34d7289ca93efa1a68196fd7116
