### ISSUE TITLE
Admin account: customer logo may not always be visible

### ISSUE THREAD

**Issue by cmh208** [brodjustice/semi_static#38]
![capture](https://user-images.githubusercontent.com/16307935/53958710-0ad49000-40e2-11e9-882f-21f611e80971.JPG)

Cosmetic and perhaps not that important - depends if the customer has an admin a/c to manage the website. The customer logo may not always be visible - an example here. Might need a different background (white?) for this space.

**Comment by brodjustice** [comment]
Closed by https://github.com/brodjustice/semi_static/issues/38
