### ISSUE TITLE
New Admin panel: Sidebar is disabled upon edit

### ISSUE THREAD

**Issue by cmh208** [brodjustice/semi_static#39]
If you edit, an entry the side bar is disabled, e.g. from Armin's site:

![Capture](https://user-images.githubusercontent.com/16307935/54112013-8afe3c80-43e5-11e9-8042-e652c1fa34dc.JPG)

You have to explicitly re-enable it.

**Comment by brodjustice** [comment]
Closed by https://github.com/brodjustice/semi_static/issues/39
